命令稿啟動於 2017年03月07日 (週二) 19時56分46秒
]0;michael@michael-VirtualBox: ~[01;32mmichael@michael-VirtualBox[00m:[01;34m~[00m$ git clone httpsL//gi[K[K[K[K[K[Ks://github.com/silentyard/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;michael@michael-VirtualBox: ~[01;32mmichael@michael-VirtualBox[00m:[01;34m~[00m$ exit

命令稿已於 2017年03月07日 (週二) 19時57分47秒
 完成